-- Add parking rates by vehicle type to MouRule
ALTER TABLE "MouRule" ADD COLUMN "firstHour_motorcycle" INTEGER NOT NULL DEFAULT 2000;
ALTER TABLE "MouRule" ADD COLUMN "nextHour_motorcycle" INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE "MouRule" ADD COLUMN "maximumDaily_motorcycle" INTEGER NOT NULL DEFAULT 10000;

ALTER TABLE "MouRule" ADD COLUMN "firstHour_car" INTEGER NOT NULL DEFAULT 3000;
ALTER TABLE "MouRule" ADD COLUMN "nextHour_car" INTEGER NOT NULL DEFAULT 1500;
ALTER TABLE "MouRule" ADD COLUMN "maximumDaily_car" INTEGER NOT NULL DEFAULT 15000;
